user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods:   [POST]
user_edit:
    path: /edit
    controller: App\Controller\UserController::edit
    methods:   [POST]